//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Credere.Tests.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.SondaSoap")]
    public interface SondaSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResetPosition", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ResetPosition();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResetPosition", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ResetPositionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetPosition", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SetPosition();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetPosition", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SetPositionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPosition", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetPosition();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPosition", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetPositionAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SondaSoapChannel : Credere.Tests.ServiceReference.SondaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SondaSoapClient : System.ServiceModel.ClientBase<Credere.Tests.ServiceReference.SondaSoap>, Credere.Tests.ServiceReference.SondaSoap {
        
        public SondaSoapClient() {
        }
        
        public SondaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SondaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SondaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SondaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ResetPosition() {
            return base.Channel.ResetPosition();
        }
        
        public System.Threading.Tasks.Task<string> ResetPositionAsync() {
            return base.Channel.ResetPositionAsync();
        }
        
        public string SetPosition() {
            return base.Channel.SetPosition();
        }
        
        public System.Threading.Tasks.Task<string> SetPositionAsync() {
            return base.Channel.SetPositionAsync();
        }
        
        public string GetPosition() {
            return base.Channel.GetPosition();
        }
        
        public System.Threading.Tasks.Task<string> GetPositionAsync() {
            return base.Channel.GetPositionAsync();
        }
    }
}
